# .rubocop.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - "app/helpers/application_helper.rb"
    - "app/mailers/application_mailer.rb"
    - "app/models/application_record.rb"
    - "app/models/menu.rb"
    - "test/**/*"
    - "spec/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
