version: '3.8'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0' -p 8080"
    volumes:
      - .:/var/www/menu_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: sqlite3:///var/www/menu_app/db/production.sqlite3
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

# No need for volumes for PostgreSQL anymore
# volumes:
#   postgres_data:
